# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BridgeMerged(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bridge': 'Bridge',
        'bridge_from': 'Bridge'
    }

    attribute_map = {
        'bridge': 'bridge',
        'bridge_from': 'bridge_from'
    }

    def __init__(self, bridge=None, bridge_from=None):  # noqa: E501
        """BridgeMerged - a model defined in Swagger"""  # noqa: E501

        self._bridge = None
        self._bridge_from = None
        self.discriminator = None

        self.bridge = bridge
        self.bridge_from = bridge_from

    @property
    def bridge(self):
        """Gets the bridge of this BridgeMerged.  # noqa: E501


        :return: The bridge of this BridgeMerged.  # noqa: E501
        :rtype: Bridge
        """
        return self._bridge

    @bridge.setter
    def bridge(self, bridge):
        """Sets the bridge of this BridgeMerged.


        :param bridge: The bridge of this BridgeMerged.  # noqa: E501
        :type: Bridge
        """
        if bridge is None:
            raise ValueError("Invalid value for `bridge`, must not be `None`")  # noqa: E501

        self._bridge = bridge

    @property
    def bridge_from(self):
        """Gets the bridge_from of this BridgeMerged.  # noqa: E501


        :return: The bridge_from of this BridgeMerged.  # noqa: E501
        :rtype: Bridge
        """
        return self._bridge_from

    @bridge_from.setter
    def bridge_from(self, bridge_from):
        """Sets the bridge_from of this BridgeMerged.


        :param bridge_from: The bridge_from of this BridgeMerged.  # noqa: E501
        :type: Bridge
        """
        if bridge_from is None:
            raise ValueError("Invalid value for `bridge_from`, must not be `None`")  # noqa: E501

        self._bridge_from = bridge_from

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BridgeMerged, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BridgeMerged):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
