# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ChannelCallerId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'caller_presentation': 'int',
        'caller_presentation_txt': 'str',
        'channel': 'Channel'
    }

    attribute_map = {
        'caller_presentation': 'caller_presentation',
        'caller_presentation_txt': 'caller_presentation_txt',
        'channel': 'channel'
    }

    def __init__(self, caller_presentation=None, caller_presentation_txt=None, channel=None):  # noqa: E501
        """ChannelCallerId - a model defined in Swagger"""  # noqa: E501

        self._caller_presentation = None
        self._caller_presentation_txt = None
        self._channel = None
        self.discriminator = None

        self.caller_presentation = caller_presentation
        self.caller_presentation_txt = caller_presentation_txt
        self.channel = channel

    @property
    def caller_presentation(self):
        """Gets the caller_presentation of this ChannelCallerId.  # noqa: E501

        The integer representation of the Caller Presentation value.  # noqa: E501

        :return: The caller_presentation of this ChannelCallerId.  # noqa: E501
        :rtype: int
        """
        return self._caller_presentation

    @caller_presentation.setter
    def caller_presentation(self, caller_presentation):
        """Sets the caller_presentation of this ChannelCallerId.

        The integer representation of the Caller Presentation value.  # noqa: E501

        :param caller_presentation: The caller_presentation of this ChannelCallerId.  # noqa: E501
        :type: int
        """
        if caller_presentation is None:
            raise ValueError("Invalid value for `caller_presentation`, must not be `None`")  # noqa: E501

        self._caller_presentation = caller_presentation

    @property
    def caller_presentation_txt(self):
        """Gets the caller_presentation_txt of this ChannelCallerId.  # noqa: E501

        The text representation of the Caller Presentation value.  # noqa: E501

        :return: The caller_presentation_txt of this ChannelCallerId.  # noqa: E501
        :rtype: str
        """
        return self._caller_presentation_txt

    @caller_presentation_txt.setter
    def caller_presentation_txt(self, caller_presentation_txt):
        """Sets the caller_presentation_txt of this ChannelCallerId.

        The text representation of the Caller Presentation value.  # noqa: E501

        :param caller_presentation_txt: The caller_presentation_txt of this ChannelCallerId.  # noqa: E501
        :type: str
        """
        if caller_presentation_txt is None:
            raise ValueError("Invalid value for `caller_presentation_txt`, must not be `None`")  # noqa: E501

        self._caller_presentation_txt = caller_presentation_txt

    @property
    def channel(self):
        """Gets the channel of this ChannelCallerId.  # noqa: E501

        The channel that changed Caller ID.  # noqa: E501

        :return: The channel of this ChannelCallerId.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ChannelCallerId.

        The channel that changed Caller ID.  # noqa: E501

        :param channel: The channel of this ChannelCallerId.  # noqa: E501
        :type: Channel
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelCallerId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelCallerId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
