# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ChannelHangupRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cause': 'int',
        'channel': 'Channel',
        'soft': 'bool'
    }

    attribute_map = {
        'cause': 'cause',
        'channel': 'channel',
        'soft': 'soft'
    }

    def __init__(self, cause=None, channel=None, soft=None):  # noqa: E501
        """ChannelHangupRequest - a model defined in Swagger"""  # noqa: E501

        self._cause = None
        self._channel = None
        self._soft = None
        self.discriminator = None

        if cause is not None:
            self.cause = cause
        self.channel = channel
        if soft is not None:
            self.soft = soft

    @property
    def cause(self):
        """Gets the cause of this ChannelHangupRequest.  # noqa: E501

        Integer representation of the cause of the hangup.  # noqa: E501

        :return: The cause of this ChannelHangupRequest.  # noqa: E501
        :rtype: int
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this ChannelHangupRequest.

        Integer representation of the cause of the hangup.  # noqa: E501

        :param cause: The cause of this ChannelHangupRequest.  # noqa: E501
        :type: int
        """

        self._cause = cause

    @property
    def channel(self):
        """Gets the channel of this ChannelHangupRequest.  # noqa: E501

        The channel on which the hangup was requested.  # noqa: E501

        :return: The channel of this ChannelHangupRequest.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ChannelHangupRequest.

        The channel on which the hangup was requested.  # noqa: E501

        :param channel: The channel of this ChannelHangupRequest.  # noqa: E501
        :type: Channel
        """
        if channel is None:
            raise ValueError("Invalid value for `channel`, must not be `None`")  # noqa: E501

        self._channel = channel

    @property
    def soft(self):
        """Gets the soft of this ChannelHangupRequest.  # noqa: E501

        Whether the hangup request was a soft hangup request.  # noqa: E501

        :return: The soft of this ChannelHangupRequest.  # noqa: E501
        :rtype: bool
        """
        return self._soft

    @soft.setter
    def soft(self, soft):
        """Sets the soft of this ChannelHangupRequest.

        Whether the hangup request was a soft hangup request.  # noqa: E501

        :param soft: The soft of this ChannelHangupRequest.  # noqa: E501
        :type: bool
        """

        self._soft = soft

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelHangupRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelHangupRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
