# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ChannelVarset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'Channel',
        'value': 'str',
        'variable': 'str'
    }

    attribute_map = {
        'channel': 'channel',
        'value': 'value',
        'variable': 'variable'
    }

    def __init__(self, channel=None, value=None, variable=None):  # noqa: E501
        """ChannelVarset - a model defined in Swagger"""  # noqa: E501

        self._channel = None
        self._value = None
        self._variable = None
        self.discriminator = None

        if channel is not None:
            self.channel = channel
        self.value = value
        self.variable = variable

    @property
    def channel(self):
        """Gets the channel of this ChannelVarset.  # noqa: E501

        The channel on which the variable was set.  If missing, the variable is a global variable.  # noqa: E501

        :return: The channel of this ChannelVarset.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this ChannelVarset.

        The channel on which the variable was set.  If missing, the variable is a global variable.  # noqa: E501

        :param channel: The channel of this ChannelVarset.  # noqa: E501
        :type: Channel
        """

        self._channel = channel

    @property
    def value(self):
        """Gets the value of this ChannelVarset.  # noqa: E501

        The new value of the variable.  # noqa: E501

        :return: The value of this ChannelVarset.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ChannelVarset.

        The new value of the variable.  # noqa: E501

        :param value: The value of this ChannelVarset.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def variable(self):
        """Gets the variable of this ChannelVarset.  # noqa: E501

        The variable that changed.  # noqa: E501

        :return: The variable of this ChannelVarset.  # noqa: E501
        :rtype: str
        """
        return self._variable

    @variable.setter
    def variable(self, variable):
        """Sets the variable of this ChannelVarset.

        The variable that changed.  # noqa: E501

        :param variable: The variable of this ChannelVarset.  # noqa: E501
        :type: str
        """
        if variable is None:
            raise ValueError("Invalid value for `variable`, must not be `None`")  # noqa: E501

        self._variable = variable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelVarset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelVarset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
