# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContactInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aor': 'str',
        'contact_status': 'str',
        'roundtrip_usec': 'str',
        'uri': 'str'
    }

    attribute_map = {
        'aor': 'aor',
        'contact_status': 'contact_status',
        'roundtrip_usec': 'roundtrip_usec',
        'uri': 'uri'
    }

    def __init__(self, aor=None, contact_status=None, roundtrip_usec=None, uri=None):  # noqa: E501
        """ContactInfo - a model defined in Swagger"""  # noqa: E501

        self._aor = None
        self._contact_status = None
        self._roundtrip_usec = None
        self._uri = None
        self.discriminator = None

        self.aor = aor
        self.contact_status = contact_status
        if roundtrip_usec is not None:
            self.roundtrip_usec = roundtrip_usec
        self.uri = uri

    @property
    def aor(self):
        """Gets the aor of this ContactInfo.  # noqa: E501

        The Address of Record this contact belongs to.  # noqa: E501

        :return: The aor of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._aor

    @aor.setter
    def aor(self, aor):
        """Sets the aor of this ContactInfo.

        The Address of Record this contact belongs to.  # noqa: E501

        :param aor: The aor of this ContactInfo.  # noqa: E501
        :type: str
        """
        if aor is None:
            raise ValueError("Invalid value for `aor`, must not be `None`")  # noqa: E501

        self._aor = aor

    @property
    def contact_status(self):
        """Gets the contact_status of this ContactInfo.  # noqa: E501

        The current status of the contact.  # noqa: E501

        :return: The contact_status of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._contact_status

    @contact_status.setter
    def contact_status(self, contact_status):
        """Sets the contact_status of this ContactInfo.

        The current status of the contact.  # noqa: E501

        :param contact_status: The contact_status of this ContactInfo.  # noqa: E501
        :type: str
        """
        if contact_status is None:
            raise ValueError("Invalid value for `contact_status`, must not be `None`")  # noqa: E501

        self._contact_status = contact_status

    @property
    def roundtrip_usec(self):
        """Gets the roundtrip_usec of this ContactInfo.  # noqa: E501

        Current round trip time, in microseconds, for the contact.  # noqa: E501

        :return: The roundtrip_usec of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._roundtrip_usec

    @roundtrip_usec.setter
    def roundtrip_usec(self, roundtrip_usec):
        """Sets the roundtrip_usec of this ContactInfo.

        Current round trip time, in microseconds, for the contact.  # noqa: E501

        :param roundtrip_usec: The roundtrip_usec of this ContactInfo.  # noqa: E501
        :type: str
        """

        self._roundtrip_usec = roundtrip_usec

    @property
    def uri(self):
        """Gets the uri of this ContactInfo.  # noqa: E501

        The location of the contact.  # noqa: E501

        :return: The uri of this ContactInfo.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this ContactInfo.

        The location of the contact.  # noqa: E501

        :param uri: The uri of this ContactInfo.  # noqa: E501
        :type: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
