# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContactStatusChange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contact_info': 'ContactInfo',
        'endpoint': 'Endpoint'
    }

    attribute_map = {
        'contact_info': 'contact_info',
        'endpoint': 'endpoint'
    }

    def __init__(self, contact_info=None, endpoint=None):  # noqa: E501
        """ContactStatusChange - a model defined in Swagger"""  # noqa: E501

        self._contact_info = None
        self._endpoint = None
        self.discriminator = None

        self.contact_info = contact_info
        self.endpoint = endpoint

    @property
    def contact_info(self):
        """Gets the contact_info of this ContactStatusChange.  # noqa: E501


        :return: The contact_info of this ContactStatusChange.  # noqa: E501
        :rtype: ContactInfo
        """
        return self._contact_info

    @contact_info.setter
    def contact_info(self, contact_info):
        """Sets the contact_info of this ContactStatusChange.


        :param contact_info: The contact_info of this ContactStatusChange.  # noqa: E501
        :type: ContactInfo
        """
        if contact_info is None:
            raise ValueError("Invalid value for `contact_info`, must not be `None`")  # noqa: E501

        self._contact_info = contact_info

    @property
    def endpoint(self):
        """Gets the endpoint of this ContactStatusChange.  # noqa: E501


        :return: The endpoint of this ContactStatusChange.  # noqa: E501
        :rtype: Endpoint
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this ContactStatusChange.


        :param endpoint: The endpoint of this ContactStatusChange.  # noqa: E501
        :type: Endpoint
        """
        if endpoint is None:
            raise ValueError("Invalid value for `endpoint`, must not be `None`")  # noqa: E501

        self._endpoint = endpoint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactStatusChange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactStatusChange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
