# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Mailbox(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'new_messages': 'int',
        'old_messages': 'int'
    }

    attribute_map = {
        'name': 'name',
        'new_messages': 'new_messages',
        'old_messages': 'old_messages'
    }

    def __init__(self, name=None, new_messages=None, old_messages=None):  # noqa: E501
        """Mailbox - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._new_messages = None
        self._old_messages = None
        self.discriminator = None

        self.name = name
        self.new_messages = new_messages
        self.old_messages = old_messages

    @property
    def name(self):
        """Gets the name of this Mailbox.  # noqa: E501

        Name of the mailbox.  # noqa: E501

        :return: The name of this Mailbox.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Mailbox.

        Name of the mailbox.  # noqa: E501

        :param name: The name of this Mailbox.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def new_messages(self):
        """Gets the new_messages of this Mailbox.  # noqa: E501

        Count of new messages in the mailbox.  # noqa: E501

        :return: The new_messages of this Mailbox.  # noqa: E501
        :rtype: int
        """
        return self._new_messages

    @new_messages.setter
    def new_messages(self, new_messages):
        """Sets the new_messages of this Mailbox.

        Count of new messages in the mailbox.  # noqa: E501

        :param new_messages: The new_messages of this Mailbox.  # noqa: E501
        :type: int
        """
        if new_messages is None:
            raise ValueError("Invalid value for `new_messages`, must not be `None`")  # noqa: E501

        self._new_messages = new_messages

    @property
    def old_messages(self):
        """Gets the old_messages of this Mailbox.  # noqa: E501

        Count of old messages in the mailbox.  # noqa: E501

        :return: The old_messages of this Mailbox.  # noqa: E501
        :rtype: int
        """
        return self._old_messages

    @old_messages.setter
    def old_messages(self, old_messages):
        """Sets the old_messages of this Mailbox.

        Count of old messages in the mailbox.  # noqa: E501

        :param old_messages: The old_messages of this Mailbox.  # noqa: E501
        :type: int
        """
        if old_messages is None:
            raise ValueError("Invalid value for `old_messages`, must not be `None`")  # noqa: E501

        self._old_messages = old_messages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Mailbox, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Mailbox):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
