# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Sound(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'formats': 'list[FormatLangPair]',
        'id': 'str',
        'text': 'str'
    }

    attribute_map = {
        'formats': 'formats',
        'id': 'id',
        'text': 'text'
    }

    def __init__(self, formats=None, id=None, text=None):  # noqa: E501
        """Sound - a model defined in Swagger"""  # noqa: E501

        self._formats = None
        self._id = None
        self._text = None
        self.discriminator = None

        self.formats = formats
        self.id = id
        if text is not None:
            self.text = text

    @property
    def formats(self):
        """Gets the formats of this Sound.  # noqa: E501

        The formats and languages in which this sound is available.  # noqa: E501

        :return: The formats of this Sound.  # noqa: E501
        :rtype: list[FormatLangPair]
        """
        return self._formats

    @formats.setter
    def formats(self, formats):
        """Sets the formats of this Sound.

        The formats and languages in which this sound is available.  # noqa: E501

        :param formats: The formats of this Sound.  # noqa: E501
        :type: list[FormatLangPair]
        """
        if formats is None:
            raise ValueError("Invalid value for `formats`, must not be `None`")  # noqa: E501

        self._formats = formats

    @property
    def id(self):
        """Gets the id of this Sound.  # noqa: E501

        Sound's identifier.  # noqa: E501

        :return: The id of this Sound.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Sound.

        Sound's identifier.  # noqa: E501

        :param id: The id of this Sound.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def text(self):
        """Gets the text of this Sound.  # noqa: E501

        Text description of the sound, usually the words spoken.  # noqa: E501

        :return: The text of this Sound.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Sound.

        Text description of the sound, usually the words spoken.  # noqa: E501

        :param text: The text of this Sound.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Sound, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Sound):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
