# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StatusInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_reload_time': 'date',
        'startup_time': 'date'
    }

    attribute_map = {
        'last_reload_time': 'last_reload_time',
        'startup_time': 'startup_time'
    }

    def __init__(self, last_reload_time=None, startup_time=None):  # noqa: E501
        """StatusInfo - a model defined in Swagger"""  # noqa: E501

        self._last_reload_time = None
        self._startup_time = None
        self.discriminator = None

        self.last_reload_time = last_reload_time
        self.startup_time = startup_time

    @property
    def last_reload_time(self):
        """Gets the last_reload_time of this StatusInfo.  # noqa: E501

        Time when Asterisk was last reloaded.  # noqa: E501

        :return: The last_reload_time of this StatusInfo.  # noqa: E501
        :rtype: date
        """
        return self._last_reload_time

    @last_reload_time.setter
    def last_reload_time(self, last_reload_time):
        """Sets the last_reload_time of this StatusInfo.

        Time when Asterisk was last reloaded.  # noqa: E501

        :param last_reload_time: The last_reload_time of this StatusInfo.  # noqa: E501
        :type: date
        """
        if last_reload_time is None:
            raise ValueError("Invalid value for `last_reload_time`, must not be `None`")  # noqa: E501

        self._last_reload_time = last_reload_time

    @property
    def startup_time(self):
        """Gets the startup_time of this StatusInfo.  # noqa: E501

        Time when Asterisk was started.  # noqa: E501

        :return: The startup_time of this StatusInfo.  # noqa: E501
        :rtype: date
        """
        return self._startup_time

    @startup_time.setter
    def startup_time(self, startup_time):
        """Sets the startup_time of this StatusInfo.

        Time when Asterisk was started.  # noqa: E501

        :param startup_time: The startup_time of this StatusInfo.  # noqa: E501
        :type: date
        """
        if startup_time is None:
            raise ValueError("Invalid value for `startup_time`, must not be `None`")  # noqa: E501

        self._startup_time = startup_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatusInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatusInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
