# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.playbacks_api import PlaybacksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaybacksApi(unittest.TestCase):
    """PlaybacksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.playbacks_api.PlaybacksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_playbacks_playback_id_control_post(self):
        """Test case for playbacks_playback_id_control_post

        Control a playback.  # noqa: E501
        """
        pass

    def test_playbacks_playback_id_delete(self):
        """Test case for playbacks_playback_id_delete

        Stop a playback.  # noqa: E501
        """
        pass

    def test_playbacks_playback_id_get(self):
        """Test case for playbacks_playback_id_get

        Get a playback's details.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
