# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.endpoint_state_change import EndpointStateChange  # noqa: E501
from swagger_client.rest import ApiException


class TestEndpointStateChange(unittest.TestCase):
    """EndpointStateChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpointStateChange(self):
        """Test EndpointStateChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.endpoint_state_change.EndpointStateChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
