# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.recordings_api import RecordingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordingsApi(unittest.TestCase):
    """RecordingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.recordings_api.RecordingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recordings_live_recording_name_delete(self):
        """Test case for recordings_live_recording_name_delete

        Stop a live recording and discard it.  # noqa: E501
        """
        pass

    def test_recordings_live_recording_name_get(self):
        """Test case for recordings_live_recording_name_get

        List live recordings.  # noqa: E501
        """
        pass

    def test_recordings_live_recording_name_mute_delete(self):
        """Test case for recordings_live_recording_name_mute_delete

        Unmute a live recording.  # noqa: E501
        """
        pass

    def test_recordings_live_recording_name_mute_post(self):
        """Test case for recordings_live_recording_name_mute_post

        Mute a live recording.  # noqa: E501
        """
        pass

    def test_recordings_live_recording_name_pause_delete(self):
        """Test case for recordings_live_recording_name_pause_delete

        Unpause a live recording.  # noqa: E501
        """
        pass

    def test_recordings_live_recording_name_pause_post(self):
        """Test case for recordings_live_recording_name_pause_post

        Pause a live recording.  # noqa: E501
        """
        pass

    def test_recordings_live_recording_name_stop_post(self):
        """Test case for recordings_live_recording_name_stop_post

        Stop a live recording and store it.  # noqa: E501
        """
        pass

    def test_recordings_stored_get(self):
        """Test case for recordings_stored_get

        List recordings that are complete.  # noqa: E501
        """
        pass

    def test_recordings_stored_recording_name_copy_post(self):
        """Test case for recordings_stored_recording_name_copy_post

        Copy a stored recording.  # noqa: E501
        """
        pass

    def test_recordings_stored_recording_name_delete(self):
        """Test case for recordings_stored_recording_name_delete

        Delete a stored recording.  # noqa: E501
        """
        pass

    def test_recordings_stored_recording_name_file_get(self):
        """Test case for recordings_stored_recording_name_file_get

        Get the file associated with the stored recording.  # noqa: E501
        """
        pass

    def test_recordings_stored_recording_name_get(self):
        """Test case for recordings_stored_recording_name_get

        Get a stored recording's details.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
