# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.channels_api import ChannelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.channels_api.ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_channels_channel_id_answer_post(self):
        """Test case for channels_channel_id_answer_post

        Answer a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_continue_post(self):
        """Test case for channels_channel_id_continue_post

        Exit application; continue execution in the dialplan.  # noqa: E501
        """
        pass

    def test_channels_channel_id_delete(self):
        """Test case for channels_channel_id_delete

        Delete (i.e. hangup) a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_dial_post(self):
        """Test case for channels_channel_id_dial_post

        Dial a created channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_dtmf_post(self):
        """Test case for channels_channel_id_dtmf_post

        Send provided DTMF to a given channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_get(self):
        """Test case for channels_channel_id_get

        Channel details.  # noqa: E501
        """
        pass

    def test_channels_channel_id_hold_delete(self):
        """Test case for channels_channel_id_hold_delete

        Remove a channel from hold.  # noqa: E501
        """
        pass

    def test_channels_channel_id_hold_post(self):
        """Test case for channels_channel_id_hold_post

        Hold a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_moh_delete(self):
        """Test case for channels_channel_id_moh_delete

        Stop playing music on hold to a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_moh_post(self):
        """Test case for channels_channel_id_moh_post

        Play music on hold to a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_move_post(self):
        """Test case for channels_channel_id_move_post

        Move the channel from one Stasis application to another.  # noqa: E501
        """
        pass

    def test_channels_channel_id_mute_delete(self):
        """Test case for channels_channel_id_mute_delete

        Unmute a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_mute_post(self):
        """Test case for channels_channel_id_mute_post

        Mute a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_play_playback_id_post(self):
        """Test case for channels_channel_id_play_playback_id_post

        Start playback of media and specify the playbackId.  # noqa: E501
        """
        pass

    def test_channels_channel_id_play_post(self):
        """Test case for channels_channel_id_play_post

        Start playback of media.  # noqa: E501
        """
        pass

    def test_channels_channel_id_post(self):
        """Test case for channels_channel_id_post

        Create a new channel (originate with id).  # noqa: E501
        """
        pass

    def test_channels_channel_id_record_post(self):
        """Test case for channels_channel_id_record_post

        Start a recording.  # noqa: E501
        """
        pass

    def test_channels_channel_id_redirect_post(self):
        """Test case for channels_channel_id_redirect_post

        Redirect the channel to a different location.  # noqa: E501
        """
        pass

    def test_channels_channel_id_ring_delete(self):
        """Test case for channels_channel_id_ring_delete

        Stop ringing indication on a channel if locally generated.  # noqa: E501
        """
        pass

    def test_channels_channel_id_ring_post(self):
        """Test case for channels_channel_id_ring_post

        Indicate ringing to a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_rtp_statistics_get(self):
        """Test case for channels_channel_id_rtp_statistics_get

        RTP stats on a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_silence_delete(self):
        """Test case for channels_channel_id_silence_delete

        Stop playing silence to a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_silence_post(self):
        """Test case for channels_channel_id_silence_post

        Play silence to a channel.  # noqa: E501
        """
        pass

    def test_channels_channel_id_snoop_post(self):
        """Test case for channels_channel_id_snoop_post

        Start snooping.  # noqa: E501
        """
        pass

    def test_channels_channel_id_snoop_snoop_id_post(self):
        """Test case for channels_channel_id_snoop_snoop_id_post

        Start snooping.  # noqa: E501
        """
        pass

    def test_channels_channel_id_variable_get(self):
        """Test case for channels_channel_id_variable_get

        Get the value of a channel variable or function.  # noqa: E501
        """
        pass

    def test_channels_channel_id_variable_post(self):
        """Test case for channels_channel_id_variable_post

        Set the value of a channel variable or function.  # noqa: E501
        """
        pass

    def test_channels_create_post(self):
        """Test case for channels_create_post

        Create channel.  # noqa: E501
        """
        pass

    def test_channels_external_media_post(self):
        """Test case for channels_external_media_post

        Start an External Media session.  # noqa: E501
        """
        pass

    def test_channels_get(self):
        """Test case for channels_get

        List all active channels in Asterisk.  # noqa: E501
        """
        pass

    def test_channels_post(self):
        """Test case for channels_post

        Create a new channel (originate).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
