# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.channel_entered_bridge import ChannelEnteredBridge  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelEnteredBridge(unittest.TestCase):
    """ChannelEnteredBridge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelEnteredBridge(self):
        """Test ChannelEnteredBridge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.channel_entered_bridge.ChannelEnteredBridge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
