# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sounds_api import SoundsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSoundsApi(unittest.TestCase):
    """SoundsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sounds_api.SoundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sounds_get(self):
        """Test case for sounds_get

        List all sounds.  # noqa: E501
        """
        pass

    def test_sounds_sound_id_get(self):
        """Test case for sounds_sound_id_get

        Get a sound's details.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
