# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.amqp_api import AmqpApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAmqpApi(unittest.TestCase):
    """AmqpApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.amqp_api.AmqpApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_amqp_app_name_post(self):
        """Test case for amqp_app_name_post

        Register a stasis application  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
