# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.device_states_api import DeviceStatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceStatesApi(unittest.TestCase):
    """DeviceStatesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.device_states_api.DeviceStatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_device_states_device_name_delete(self):
        """Test case for device_states_device_name_delete

        Destroy a device-state controlled by ARI.  # noqa: E501
        """
        pass

    def test_device_states_device_name_get(self):
        """Test case for device_states_device_name_get

        Retrieve the current state of a device.  # noqa: E501
        """
        pass

    def test_device_states_device_name_put(self):
        """Test case for device_states_device_name_put

        Change the state of a device controlled by ARI. (Note - implicitly creates the device state).  # noqa: E501
        """
        pass

    def test_device_states_get(self):
        """Test case for device_states_get

        List all ARI controlled device states.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
