# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.stasis_end import StasisEnd  # noqa: E501
from swagger_client.rest import ApiException


class TestStasisEnd(unittest.TestCase):
    """StasisEnd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStasisEnd(self):
        """Test StasisEnd"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.stasis_end.StasisEnd()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
