from setuptools import setup, find_packages

setup(
    name="wazo-applicationd",
    version="1.0.0",
    description="App SDK",
    author="Wazo Authors",
    author_email="dev@wazo.community",
    url="http://www.wazo-platform.org",
    install_requires=[
        "async-timeout==3.0.1",
        "asynqp==0.6",
        "attrs==19.3.0",
        "beautifulsoup4==4.8.2",
        "certifi==2019.11.28",
        "chardet==3.0.4",
        "Click==7.0",
        "fastapi==0.46.0",
        "h11==0.9.0",
        "httptools==0.0.13",
        "idna==2.8",
        "importlib-metadata==1.3.0",
        "kombu==4.6.7",
        "more-itertools==8.0.2",
        "multidict==4.7.3",
        "pydantic==1.3",
        "python-consul==1.1.0",
        "python-dateutil==2.8.1",
        "PyYAML==5.1.2",
        "requests==2.22.0",
        "six==1.13.0",
        "soupsieve==1.9.5",
        "starlette==0.12.9",
        "urllib3==1.25.7",
        "uvicorn==0.11.1",
        "uvloop==0.14.0",
        "vine==1.3.0",
        "websockets==8.1",
        "yarl==1.4.2",
        "zipp==0.6.0",
        "gila==0.4.0"
    ],
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Operating System :: OS Independent",
    ],
    entry_points={'console_scripts': ['wazo-applicationd=wazo_applicationd.main:main']}
)
