# coding: utf-8

"""
    localhost:8088

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DeviceStatesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def device_states_device_name_delete(self, device_name, **kwargs):  # noqa: E501
        """Destroy a device-state controlled by ARI.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_device_name_delete(device_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str device_name: Name of the device (required)
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.device_states_device_name_delete_with_http_info(device_name, **kwargs)  # noqa: E501
        else:
            (data) = self.device_states_device_name_delete_with_http_info(device_name, **kwargs)  # noqa: E501
            return data

    def device_states_device_name_delete_with_http_info(self, device_name, **kwargs):  # noqa: E501
        """Destroy a device-state controlled by ARI.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_device_name_delete_with_http_info(device_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str device_name: Name of the device (required)
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_name', 'x_asterisk_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_states_device_name_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_name' is set
        if ('device_name' not in params or
                params['device_name'] is None):
            raise ValueError("Missing the required parameter `device_name` when calling `device_states_device_name_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'device_name' in params:
            path_params['deviceName'] = params['device_name']  # noqa: E501

        query_params = []

        header_params = {}
        if 'x_asterisk_id' in params:
            header_params['X-Asterisk-ID'] = params['x_asterisk_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/deviceStates/{deviceName}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def device_states_device_name_get(self, device_name, **kwargs):  # noqa: E501
        """Retrieve the current state of a device.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_device_name_get(device_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str device_name: Name of the device (required)
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: DeviceState
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.device_states_device_name_get_with_http_info(device_name, **kwargs)  # noqa: E501
        else:
            (data) = self.device_states_device_name_get_with_http_info(device_name, **kwargs)  # noqa: E501
            return data

    def device_states_device_name_get_with_http_info(self, device_name, **kwargs):  # noqa: E501
        """Retrieve the current state of a device.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_device_name_get_with_http_info(device_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str device_name: Name of the device (required)
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: DeviceState
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_name', 'x_asterisk_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_states_device_name_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_name' is set
        if ('device_name' not in params or
                params['device_name'] is None):
            raise ValueError("Missing the required parameter `device_name` when calling `device_states_device_name_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'device_name' in params:
            path_params['deviceName'] = params['device_name']  # noqa: E501

        query_params = []

        header_params = {}
        if 'x_asterisk_id' in params:
            header_params['X-Asterisk-ID'] = params['x_asterisk_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/deviceStates/{deviceName}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DeviceState',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def device_states_device_name_put(self, device_name, device_state, **kwargs):  # noqa: E501
        """Change the state of a device controlled by ARI. (Note - implicitly creates the device state).  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_device_name_put(device_name, device_state, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str device_name: Name of the device (required)
        :param str device_state: Device state value (required)
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.device_states_device_name_put_with_http_info(device_name, device_state, **kwargs)  # noqa: E501
        else:
            (data) = self.device_states_device_name_put_with_http_info(device_name, device_state, **kwargs)  # noqa: E501
            return data

    def device_states_device_name_put_with_http_info(self, device_name, device_state, **kwargs):  # noqa: E501
        """Change the state of a device controlled by ARI. (Note - implicitly creates the device state).  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_device_name_put_with_http_info(device_name, device_state, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str device_name: Name of the device (required)
        :param str device_state: Device state value (required)
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['device_name', 'device_state', 'x_asterisk_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_states_device_name_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'device_name' is set
        if ('device_name' not in params or
                params['device_name'] is None):
            raise ValueError("Missing the required parameter `device_name` when calling `device_states_device_name_put`")  # noqa: E501
        # verify the required parameter 'device_state' is set
        if ('device_state' not in params or
                params['device_state'] is None):
            raise ValueError("Missing the required parameter `device_state` when calling `device_states_device_name_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'device_name' in params:
            path_params['deviceName'] = params['device_name']  # noqa: E501

        query_params = []
        if 'device_state' in params:
            query_params.append(('deviceState', params['device_state']))  # noqa: E501

        header_params = {}
        if 'x_asterisk_id' in params:
            header_params['X-Asterisk-ID'] = params['x_asterisk_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/deviceStates/{deviceName}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def device_states_get(self, **kwargs):  # noqa: E501
        """List all ARI controlled device states.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: list[DeviceState]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.device_states_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.device_states_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def device_states_get_with_http_info(self, **kwargs):  # noqa: E501
        """List all ARI controlled device states.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.device_states_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_asterisk_id: Asterisk ID used to route the request through the API Gateway
        :return: list[DeviceState]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_asterisk_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method device_states_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'x_asterisk_id' in params:
            header_params['X-Asterisk-ID'] = params['x_asterisk_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['basicAuth']  # noqa: E501

        return self.api_client.call_api(
            '/deviceStates', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DeviceState]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
